policy_path: "{LEGGED_GYM_ROOT_DIR}/pre_train/a1/{model_name}"
xml_path: "{LEGGED_GYM_ROOT_DIR}/resources/unitree_a1/scene.xml"
model_name: "model_0702.pt"
framework: "isaacgym"
# Total simulation time
simulation_duration: 60.0
# Simulation time step
simulation_dt: 0.005
viewer_dt: 0.02  # 50 fps for viewer
# Controller update frequency (meets the requirement of simulation_dt * controll_decimation=0.02; 50Hz)
control_decimation: 4
rows: 4
cols: 3
num_obs: 45
num_actions: 12
observations: ["ang_vel", "gravity_vec", "commands", "dof_pos", "dof_vel", "actions"]
observations_history: [0, 1, 2, 3, 4, 5]
clip_obs: 100.0
clip_actions_lower: [-100, -100, -100,
                      -100, -100, -100,
                      -100, -100, -100,
                      -100, -100, -100]
clip_actions_upper: [100, 100, 100,
                      100, 100, 100,
                      100, 100, 100,
                      100, 100, 100]

rl_kp: [20.1, 20.1, 20.1,
        20.1, 20.1, 20.1,
        20.1, 20.1, 20.1,
        20.1, 20.1, 20.1]
rl_kd: [0.754, 0.754, 0.754,
        0.754, 0.754, 0.754,
        0.754, 0.754, 0.754,
        0.754, 0.754, 0.754]

# rl_kp: [40, 40, 40,
#         40, 40, 40,
#         40, 40, 40,
#         40, 40, 40]

# rl_kd: [0.8, 0.8, 0.8, # 前左腿
#         0.8, 0.8, 0.8, # 前右腿
#         0.8, 0.8, 0.8, # 后左腿
#         0.8, 0.8, 0.8] # 后右腿

fixed_kp: [80, 80, 80,
            80, 80, 80,
            80, 80, 80,
            80, 80, 80]
fixed_kd: [3, 3, 3,
            3, 3, 3,
            3, 3, 3,
            3, 3, 3]
hip_scale_reduction: 0.5
hip_scale_reduction_indices: [0, 3, 6, 9]
action_scale: 0.25
action_scale_wheel: 0.0
wheel_indices: []
lin_vel_scale: 2.0
ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
torque_limits: [33.5, 33.5, 33.5,
                33.5, 33.5, 33.5,
                33.5, 33.5, 33.5,
                33.5, 33.5, 33.5]
default_dof_pos: [ 0.1000, 0.8000, -1.5000,
                  -0.1000, 0.8000, -1.5000,
                    0.1000, 1.0000, -1.5000,
                  -0.1000, 1.0000, -1.5000]
joint_controller_names: ["FL_hip_controller", "FL_thigh_controller", "FL_calf_controller",
                          "FR_hip_controller", "FR_thigh_controller", "FR_calf_controller",
                          "RL_hip_controller", "RL_thigh_controller", "RL_calf_controller",
                          "RR_hip_controller", "RR_thigh_controller", "RR_calf_controller"]
cmd_init: [0, 0, 0]